import React, { useState, useRef, useEffect } from 'react'
import { askQuestion } from '../api'

const DIFFICULTY_HELPERS = {
  easy: 'Simple words, short answer, everyday examples.',
  medium: 'Clear explanation with examples and terminology.',
  hard: 'Full detailed explanation — definitions, steps, pros/cons, applications.',
}

const LOADING_MESSAGES = [
  'Searching through textbook pages…',
  'Pruning irrelevant content…',
  'Thinking of the best explanation…',
  'Almost ready…',
]

export default function AnswerPanel({ selectedSubject, onSaveHistory }) {
  const [question, setQuestion] = useState('')
  const [difficulty, setDifficulty] = useState('medium')
  const [state, setState] = useState('welcome') // 'welcome' | 'loading' | 'answer'
  const [answer, setAnswer] = useState(null)
  const [loadingMsg, setLoadingMsg] = useState(LOADING_MESSAGES[0])
  const [isSpeaking, setIsSpeaking] = useState(false)
  const [isRecording, setIsRecording] = useState(false)
  const [micStatus, setMicStatus] = useState('Click mic to ask by voice')

  const intervalRef = useRef(null)
  const recognitionRef = useRef(null)

  // Cycle loading messages
  useEffect(() => {
    if (state === 'loading') {
      let idx = 0
      intervalRef.current = setInterval(() => {
        idx = (idx + 1) % LOADING_MESSAGES.length
        setLoadingMsg(LOADING_MESSAGES[idx])
      }, 1800)
    } else {
      clearInterval(intervalRef.current)
    }
    return () => clearInterval(intervalRef.current)
  }, [state])

  // Animate savings bar after answer loads
  useEffect(() => {
    if (state === 'answer' && answer) {
      const bar = document.getElementById('savingsBar')
      if (bar) {
        setTimeout(() => {
          bar.style.width = Math.min(answer.cost_saved_pct, 100) + '%'
        }, 100)
      }
    }
  }, [state, answer])

  async function handleAsk() {
    if (!question.trim()) { alert('Please enter a question.'); return }
    if (!selectedSubject) { alert('Please select a subject from the left panel.'); return }
    if (isSpeaking) window.speechSynthesis.cancel()

    setState('loading')
    setLoadingMsg(LOADING_MESSAGES[0])
    try {
      const data = await askQuestion(question, selectedSubject, difficulty)
      setAnswer(data)
      setState('answer')
      onSaveHistory({
        question,
        subject: selectedSubject,
        difficulty,
        answer: data.answer,
        cost_saved_pct: data.cost_saved_pct,
        original_tokens_est: data.original_tokens_est,
        pruned_tokens_est: data.pruned_tokens_est,
        from_cache: data.from_cache,
        time: new Date().toISOString(),
      })
    } catch (err) {
      setState('welcome')
      alert(err.message || 'Network error. Is the backend running on port 8000?')
    }
  }

  function toggleTTS() {
    if (!answer) return
    if (isSpeaking) {
      window.speechSynthesis.cancel()
      setIsSpeaking(false)
      return
    }
    const utt = new SpeechSynthesisUtterance(answer.answer)
    utt.lang = 'en-IN'
    utt.rate = 0.92
    utt.onstart = () => setIsSpeaking(true)
    utt.onend = utt.onerror = () => setIsSpeaking(false)
    window.speechSynthesis.speak(utt)
  }

  function toggleMic() {
    const SR = window.SpeechRecognition || window.webkitSpeechRecognition
    if (!SR) { alert('Voice input requires Chrome browser.'); return }

    if (isRecording) { recognitionRef.current?.stop(); return }

    const rec = new SR()
    recognitionRef.current = rec
    rec.lang = 'en-IN'
    rec.continuous = false
    rec.interimResults = false
    rec.onstart = () => { setIsRecording(true); setMicStatus('Speak now — click to stop') }
    rec.onresult = e => {
      const t = e.results[0][0].transcript
      setQuestion(t)
      setMicStatus(`Heard: "${t}"`)
    }
    rec.onerror = () => setMicStatus('Could not hear — try again.')
    rec.onend = () => { setIsRecording(false); setMicStatus('Click mic to ask by voice') }
    rec.start()
  }

  function downloadAnswer() {
    if (!answer) return
    const content = [
      'SHIKSHA AI — EDUCATION TUTOR',
      '='.repeat(50),
      '',
      `Question: ${question}`,
      `Subject:  ${selectedSubject}`,
      `Level:    ${difficulty.toUpperCase()}`,
      `Date:     ${new Date().toLocaleDateString('en-IN')}`,
      '',
      '─'.repeat(50),
      '',
      'ANSWER:',
      '',
      answer.answer,
      '',
      '─'.repeat(50),
      'Generated by ShikshaAI Education Tutor',
    ].join('\n')

    const blob = new Blob([content], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `shiksha_answer_${Date.now()}.txt`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div style={styles.rightPanel}>
      {/* Question card */}
      <div style={styles.card}>
        <div style={styles.cardTitle}><span style={styles.icon}>🎓</span> Ask a Question</div>

        {/* Difficulty selector */}
        <div style={styles.field}>
          <label style={styles.label}>Difficulty level</label>
          <div style={styles.diffRow}>
            {['easy', 'medium', 'hard'].map(d => (
              <div
                key={d}
                onClick={() => setDifficulty(d)}
                style={{ ...styles.diffBtn, ...getDiffStyle(d, difficulty) }}
              >
                {d === 'easy' ? '🌱 Easy' : d === 'medium' ? '📘 Medium' : '🔥 Hard'}
              </div>
            ))}
          </div>
          <div style={styles.helper}>{DIFFICULTY_HELPERS[difficulty]}</div>
        </div>

        {/* Voice input row */}
        <div style={styles.field}>
          <label style={styles.label}>Question</label>
          <div style={styles.voiceRow}>
            <button
              onClick={toggleMic}
              style={{ ...styles.voiceBtn, ...(isRecording ? styles.voiceBtnRecording : {}) }}
            >
              <span style={styles.micDot} /> 
              {isRecording ? '🔴 Listening…' : '🎙 Speak'}
            </button>
            <span style={{ fontSize: '0.75rem', color: 'var(--ink-muted)' }}>{micStatus}</span>
          </div>
          <textarea
            style={styles.textarea}
            rows={3}
            placeholder="Type your question or use the mic above…"
            value={question}
            onChange={e => setQuestion(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter' && e.ctrlKey) handleAsk() }}
          />
        </div>

        <button
          style={{ ...styles.btn, opacity: state === 'loading' ? 0.55 : 1 }}
          onClick={handleAsk}
          disabled={state === 'loading'}
        >
          {state === 'loading'
            ? <><span style={styles.spinner} /> Thinking…</>
            : 'Get Answer'}
        </button>
      </div>

      {/* Answer card */}
      <div style={styles.card}>
        <div style={styles.cardTitle}><span style={styles.icon}>✨</span> Answer</div>

        {/* Welcome state */}
        {state === 'welcome' && (
          <div style={styles.welcome}>
            <div style={{ fontSize: '2.2rem', marginBottom: '0.4rem' }}>🌾</div>
            <h3 style={styles.welcomeH3}>Ready to help you learn</h3>
            <p style={styles.welcomeP}>Upload a textbook, select a subject, then ask anything.</p>
          </div>
        )}

        {/* Loading state */}
        {state === 'loading' && (
          <div style={styles.loadingOverlay}>
            <div style={styles.bookLoader} />
            <div style={styles.loadingDots}>
              <span style={{ ...styles.dot, animationDelay: '0s' }} />
              <span style={{ ...styles.dot, animationDelay: '0.15s', background: 'var(--teal)' }} />
              <span style={{ ...styles.dot, animationDelay: '0.3s' }} />
            </div>
            <div style={styles.loadingText}>{loadingMsg}</div>
          </div>
        )}

        {/* Answer state */}
        {state === 'answer' && answer && (
          <div style={{ animation: 'fadeIn 0.35s ease' }}>
            {/* Meta badges */}
            <div style={styles.answerMeta}>
              <span style={styles.shikshaLabel}>ShikshaAI</span>
              <span style={{ ...styles.diffBadge, ...getDiffBadgeStyle(difficulty) }}>
                {difficulty.charAt(0).toUpperCase() + difficulty.slice(1)}
              </span>
              {answer.from_cache && <span style={styles.cacheBadge}>⚡ Cached</span>}
            </div>

            {/* Answer bubble */}
            <div style={styles.answerBubble}>{answer.answer}</div>

            {/* Action buttons */}
            <div style={styles.answerActions}>
              <button
                onClick={toggleTTS}
                style={{ ...styles.outlineBtn, ...(isSpeaking ? styles.speakingBtn : {}) }}
              >
                {isSpeaking ? '⏹ Stop Reading' : '🔊 Read Aloud'}
              </button>
              <button onClick={downloadAnswer} style={styles.outlineBtn}>
                ⬇ Download Answer
              </button>
            </div>

            <div style={styles.divider} />

            {/* Cost savings section */}
            <div style={{ ...styles.cardTitle, border: 'none', padding: 0, marginBottom: '0.75rem', fontSize: '0.88rem' }}>
              <span style={styles.icon}>💰</span> Cost savings
            </div>
            <div style={styles.metricsGrid}>
              <MetricCard label="Baseline tokens" value={answer.original_tokens_est.toLocaleString()} />
              <MetricCard label="Pruned tokens" value={answer.pruned_tokens_est.toLocaleString()} valueStyle={{ color: 'var(--saffron)' }} />
              <MetricCard label="Cost saved" value={answer.cost_saved_pct + '%'} valueStyle={{ color: 'var(--teal)' }} />
            </div>
            <div style={styles.savingsBarWrap}>
              <div id="savingsBar" style={{ ...styles.savingsBarFill, width: '0%' }} />
            </div>
            <div style={{ fontSize: '0.72rem', color: 'var(--teal)', marginTop: '0.3rem', fontWeight: 500 }}>
              {answer.cost_saved_pct}% fewer tokens vs baseline RAG
            </div>
            <div style={styles.helper}>
              Pruner kept {answer.sentences_kept} of {answer.sentences_total} sentences.
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

function MetricCard({ label, value, valueStyle }) {
  return (
    <div style={metricStyles.card}>
      <span style={{ ...metricStyles.value, ...valueStyle }}>{value}</span>
      <div style={metricStyles.label}>{label}</div>
    </div>
  )
}

// Helpers for dynamic styles
function getDiffStyle(d, active) {
  if (d !== active) return {}
  const map = {
    easy:   { background: 'var(--green-lt)',   borderColor: 'var(--green)',   color: 'var(--green)' },
    medium: { background: 'var(--saffron-lt)', borderColor: 'var(--saffron)', color: 'var(--saffron)' },
    hard:   { background: 'var(--red-lt)',     borderColor: 'var(--red)',     color: 'var(--red)' },
  }
  return map[d]
}

function getDiffBadgeStyle(d) {
  const map = {
    easy:   { background: 'var(--green-lt)',   color: 'var(--green)' },
    medium: { background: 'var(--saffron-lt)', color: 'var(--saffron)' },
    hard:   { background: 'var(--red-lt)',     color: 'var(--red)' },
  }
  return map[d] || {}
}

const styles = {
  rightPanel: { display: 'flex', flexDirection: 'column', gap: '1.25rem' },
  card: {
    background: 'var(--surface)',
    border: '1px solid var(--border)',
    borderRadius: 'var(--radius)',
    padding: '1.25rem',
    boxShadow: 'var(--shadow)',
    transition: 'background 0.3s, border-color 0.3s',
    animation: 'riseIn 0.35s ease both',
  },
  cardTitle: {
    fontFamily: "'Lora', serif",
    fontSize: '0.95rem',
    fontWeight: 600,
    color: 'var(--ink)',
    marginBottom: '1rem',
    paddingBottom: '0.65rem',
    borderBottom: '1px solid var(--border)',
    display: 'flex',
    alignItems: 'center',
    gap: '0.45rem',
  },
  icon: {
    width: 20, height: 20,
    background: 'var(--saffron-lt)',
    borderRadius: 5,
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 11,
  },
  field: { marginBottom: '0.85rem' },
  label: {
    display: 'block',
    fontSize: '0.75rem',
    fontWeight: 500,
    color: 'var(--ink-soft)',
    marginBottom: '0.35rem',
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  diffRow: { display: 'flex', gap: '0.5rem', marginBottom: '0.5rem' },
  diffBtn: {
    flex: 1,
    padding: '0.5rem 0.4rem',
    borderRadius: 7,
    fontSize: '0.78rem',
    fontWeight: 500,
    cursor: 'pointer',
    border: '1.5px solid var(--border)',
    background: 'var(--paper)',
    color: 'var(--ink-soft)',
    transition: 'all 0.18s',
    textAlign: 'center',
    fontFamily: "'DM Sans', sans-serif",
  },
  helper: { fontSize: '0.76rem', color: 'var(--ink-muted)', marginTop: '0.3rem' },
  voiceRow: { display: 'flex', gap: '0.5rem', alignItems: 'center', marginBottom: '0.5rem' },
  voiceBtn: {
    display: 'flex', alignItems: 'center', gap: '0.35rem',
    padding: '0.45rem 0.85rem',
    borderRadius: 7, fontSize: '0.8rem', fontWeight: 500,
    cursor: 'pointer',
    border: '1px solid var(--border)',
    background: 'var(--paper)',
    color: 'var(--ink-soft)',
    fontFamily: "'DM Sans', sans-serif",
  },
  voiceBtnRecording: {
    background: 'var(--red-lt)',
    borderColor: 'var(--red)',
    color: 'var(--red)',
  },
  micDot: {
    width: 8, height: 8,
    borderRadius: '50%',
    background: 'currentColor',
    animation: 'pulse 1s infinite',
  },
  textarea: {
    width: '100%',
    padding: '0.6rem 0.8rem',
    border: '1px solid var(--border)',
    borderRadius: 7,
    background: 'var(--paper)',
    fontFamily: "'DM Sans', sans-serif",
    fontSize: '0.9rem',
    color: 'var(--ink)',
    outline: 'none',
    resize: 'vertical',
    minHeight: 75,
    lineHeight: 1.5,
  },
  btn: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '0.4rem',
    padding: '0.6rem 1.1rem', borderRadius: 7,
    fontFamily: "'DM Sans', sans-serif", fontSize: '0.86rem', fontWeight: 500,
    cursor: 'pointer', border: 'none',
    background: 'var(--saffron)', color: '#fff', width: '100%',
  },
  spinner: {
    display: 'inline-block', width: 15, height: 15,
    border: '2px solid rgba(255,255,255,0.4)', borderTopColor: '#fff',
    borderRadius: '50%', animation: 'spin 0.7s linear infinite', flexShrink: 0,
  },
  welcome: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    justifyContent: 'center', padding: '2.5rem 1.5rem', textAlign: 'center', gap: '0.4rem',
  },
  welcomeH3: { fontFamily: "'Lora', serif", fontSize: '1rem', color: 'var(--ink-soft)', fontWeight: 600 },
  welcomeP: { fontSize: '0.82rem', color: 'var(--ink-muted)', maxWidth: 260, lineHeight: 1.5 },
  loadingOverlay: {
    display: 'flex', flexDirection: 'column', alignItems: 'center',
    justifyContent: 'center', padding: '2.5rem 1rem', gap: '0.85rem',
  },
  bookLoader: {
    position: 'relative', width: 52, height: 52,
  },
  loadingDots: { display: 'flex', gap: 5, alignItems: 'center' },
  dot: {
    width: 6, height: 6, borderRadius: '50%',
    background: 'var(--saffron)',
    animation: 'dotBounce 1.2s ease-in-out infinite',
    display: 'inline-block',
  },
  loadingText: {
    fontSize: '0.82rem', color: 'var(--ink-muted)',
    fontStyle: 'italic', animation: 'fadeText 2s ease-in-out infinite',
  },
  answerMeta: { display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.5rem', flexWrap: 'wrap' },
  shikshaLabel: {
    fontSize: '0.7rem', fontWeight: 500,
    background: 'var(--teal-lt)', color: 'var(--teal)',
    padding: '0.18rem 0.55rem', borderRadius: 20,
    textTransform: 'uppercase', letterSpacing: '0.04em',
  },
  diffBadge: {
    fontSize: '0.7rem', fontWeight: 500,
    padding: '0.18rem 0.55rem', borderRadius: 20,
  },
  cacheBadge: {
    fontSize: '0.7rem', fontWeight: 500,
    background: 'var(--blue-lt)', color: 'var(--blue)',
    padding: '0.18rem 0.55rem', borderRadius: 20,
  },
  answerBubble: {
    background: 'var(--paper)',
    border: '1px solid var(--border)',
    borderLeft: '3px solid var(--teal)',
    borderRadius: '0 9px 9px 9px',
    padding: '1rem 1.15rem',
    fontSize: '0.93rem',
    lineHeight: 1.75,
    color: 'var(--ink)',
    fontFamily: "'Lora', serif",
  },
  answerActions: { display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginTop: '0.75rem' },
  outlineBtn: {
    background: 'transparent',
    border: '1px solid var(--border)',
    color: 'var(--ink-soft)',
    padding: '0.35rem 0.75rem',
    borderRadius: 7,
    fontSize: '0.78rem',
    cursor: 'pointer',
    fontFamily: "'DM Sans', sans-serif",
  },
  speakingBtn: {
    background: 'var(--teal-lt)',
    borderColor: 'var(--teal)',
    color: 'var(--teal)',
  },
  divider: { height: 1, background: 'var(--border)', margin: '1rem 0' },
  metricsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '0.6rem' },
  savingsBarWrap: {
    marginTop: '0.75rem',
    background: 'var(--paper-3)',
    borderRadius: 4, height: 5, overflow: 'hidden',
  },
  savingsBarFill: {
    height: '100%', background: 'var(--teal)',
    borderRadius: 4, transition: 'width 0.8s cubic-bezier(0.4,0,0.2,1)',
  },
}

const metricStyles = {
  card: {
    background: 'var(--paper)', border: '1px solid var(--border)',
    borderRadius: 7, padding: '0.65rem', textAlign: 'center',
  },
  value: {
    fontSize: '1.2rem', fontWeight: 500, color: 'var(--ink)',
    fontFamily: "'Lora', serif", display: 'block', lineHeight: 1.1,
  },
  label: { fontSize: '0.7rem', color: 'var(--ink-muted)', marginTop: '0.2rem', textTransform: 'uppercase', letterSpacing: '0.04em' },
}
