import React, { useState, useRef } from 'react'
import { askQuestion } from '../api/client'
import { useSpeechRecognition, useTTS } from '../hooks/useVoice'
import BookLoader from './BookLoader'
import SubjectPills from './SubjectPills'
import { cardTitleStyle, iconStyle, labelStyle, primaryBtnStyle, spinnerStyle } from './UploadCard'

const DIFF_HELPERS = {
  easy: 'Simple words, short answer, everyday examples.',
  medium: 'Clear explanation with examples and terminology.',
  hard: 'Full detailed explanation — definitions, steps, pros/cons, applications.',
}

function downloadTxt(question, subject, difficulty, answer) {
  const sep = '─'.repeat(50)
  const content = [
    'SHIKSHA AI — EDUCATION TUTOR',
    '='.repeat(50),
    '',
    `Question: ${question}`,
    `Subject:  ${subject}`,
    `Level:    ${difficulty.toUpperCase()}`,
    `Date:     ${new Date().toLocaleDateString('en-IN')}`,
    '',
    sep,
    '',
    'ANSWER:',
    '',
    answer,
    '',
    sep,
    'Generated by ShikshaAI Education Tutor',
  ].join('\n')

  const url = URL.createObjectURL(new Blob([content], { type: 'text/plain' }))
  const a = document.createElement('a')
  a.href = url; a.download = `shiksha_answer_${Date.now()}.txt`; a.click()
  URL.revokeObjectURL(url)
}

export default function AskCard({ subjects, selectedSubject, onSelectSubject, onSaveHistory }) {
  const [question, setQuestion] = useState('')
  const [difficulty, setDifficulty] = useState('medium')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)

  const { isSpeaking, speak } = useTTS()
  const { isRecording, status: micStatus, toggle: toggleMic } = useSpeechRecognition(setQuestion)

  async function handleAsk() {
    if (!question.trim()) { alert('Please enter a question.'); return }
    if (!selectedSubject) { alert('Please select a subject from the left panel.'); return }
    if (isSpeaking) window.speechSynthesis.cancel()
    setLoading(true)
    setResult(null)
    try {
      const data = await askQuestion(question.trim(), selectedSubject, difficulty)
      setResult(data)
      onSaveHistory({
        question: question.trim(), subject: selectedSubject, difficulty,
        answer: data.answer, cost_saved_pct: data.cost_saved_pct,
        original_tokens_est: data.original_tokens_est,
        pruned_tokens_est: data.pruned_tokens_est,
        from_cache: data.from_cache,
        time: new Date().toISOString(),
      })
    } catch (e) {
      alert(e.message || 'Network error. Is the backend running on port 8000?')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '300px 1fr', gap: '1.25rem' }}>

      {/* Left panel */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        <div style={cardStyle}>
          <div style={cardTitleStyle}><span style={iconStyle}>📖</span> Subject</div>
          <SubjectPills subjects={subjects} selected={selectedSubject} onSelect={onSelectSubject} />
          {selectedSubject && (
            <input readOnly value={selectedSubject}
              style={{ ...inputStyleLocal, marginTop: '.5rem', background: 'var(--paper-2)', cursor: 'default' }} />
          )}
        </div>

        <div style={cardStyle}>
          <div style={cardTitleStyle}><span style={iconStyle}>🎚</span> Difficulty</div>
          <div style={{ display: 'flex', gap: '.5rem', marginBottom: '.5rem' }}>
            {['easy', 'medium', 'hard'].map(d => (
              <button key={d} onClick={() => setDifficulty(d)} style={{
                flex: 1, padding: '.5rem .4rem', borderRadius: 7,
                fontSize: '.78rem', fontWeight: 500, cursor: 'pointer',
                fontFamily: "'DM Sans', sans-serif", textAlign: 'center',
                transition: 'all .18s',
                border: `1.5px solid ${difficulty === d
                  ? d === 'easy' ? 'var(--green)' : d === 'medium' ? 'var(--saffron)' : 'var(--red)'
                  : 'var(--border)'}`,
                background: difficulty === d
                  ? d === 'easy' ? 'var(--green-lt)' : d === 'medium' ? 'var(--saffron-lt)' : 'var(--red-lt)'
                  : 'var(--paper)',
                color: difficulty === d
                  ? d === 'easy' ? 'var(--green)' : d === 'medium' ? 'var(--saffron)' : 'var(--red)'
                  : 'var(--ink-soft)',
              }}>
                {d === 'easy' ? '🌱' : d === 'medium' ? '📘' : '🔥'} {d.charAt(0).toUpperCase() + d.slice(1)}
              </button>
            ))}
          </div>
          <p style={{ fontSize: '.76rem', color: 'var(--ink-muted)' }}>{DIFF_HELPERS[difficulty]}</p>
        </div>
      </div>

      {/* Right panel */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>

        {/* Question input */}
        <div style={cardStyle}>
          <div style={cardTitleStyle}><span style={iconStyle}>❓</span> Ask a Question</div>

          <div style={{ display: 'flex', gap: '.5rem', alignItems: 'center', marginBottom: '.75rem' }}>
            <button onClick={toggleMic} style={{
              display: 'flex', alignItems: 'center', gap: '.35rem',
              padding: '.45rem .85rem', borderRadius: 7, fontSize: '.8rem', fontWeight: 500,
              cursor: 'pointer', fontFamily: "'DM Sans', sans-serif",
              border: `1px solid ${isRecording ? 'var(--red)' : 'var(--border)'}`,
              background: isRecording ? 'var(--red-lt)' : 'var(--paper)',
              color: isRecording ? 'var(--red)' : 'var(--ink-soft)',
              transition: 'all .18s',
            }}>
              <span style={{
                width: 8, height: 8, borderRadius: '50%', background: 'currentColor',
                animation: isRecording ? 'pulse 1s infinite' : 'none',
              }} />
              {isRecording ? '🔴 Listening…' : '🎙 Speak'}
            </button>
            <span style={{ fontSize: '.75rem', color: 'var(--ink-muted)' }}>{micStatus}</span>
          </div>

          <textarea
            value={question}
            onChange={e => setQuestion(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && e.ctrlKey && handleAsk()}
            rows={3}
            placeholder="Type your question or use the mic above… (Ctrl+Enter to submit)"
            style={{
              width: '100%', padding: '.6rem .8rem',
              border: '1px solid var(--border)', borderRadius: 7,
              background: 'var(--paper)', fontFamily: "'DM Sans', sans-serif",
              fontSize: '.9rem', color: 'var(--ink)', outline: 'none',
              resize: 'vertical', minHeight: 75, lineHeight: 1.5,
              transition: 'border-color .2s, background .3s',
              marginBottom: '.85rem',
            }}
          />

          <button onClick={handleAsk} disabled={loading} style={primaryBtnStyle}>
            {loading ? <><span style={spinnerStyle} /> Thinking…</> : 'Get Answer'}
          </button>
        </div>

        {/* Answer panel */}
        <div style={cardStyle}>
          <div style={cardTitleStyle}><span style={iconStyle}>✨</span> Answer</div>

          {!loading && !result && (
            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', padding: '2.5rem 1.5rem', textAlign: 'center', gap: '.4rem' }}>
              <span style={{ fontSize: '2.2rem', marginBottom: '.4rem' }}>🌾</span>
              <h3 style={{ fontFamily: "'Lora', serif", fontSize: '1rem', color: 'var(--ink-soft)', fontWeight: 600 }}>
                Ready to help you learn
              </h3>
              <p style={{ fontSize: '.82rem', color: 'var(--ink-muted)', maxWidth: 260, lineHeight: 1.5 }}>
                Upload a textbook, select a subject, then ask anything.
              </p>
            </div>
          )}

          <BookLoader visible={loading} />

          {!loading && result && (
            <div style={{ animation: 'fadeIn .35s ease' }}>
              {/* Badges */}
              <div style={{ display: 'flex', alignItems: 'center', gap: '.5rem', marginBottom: '.5rem', flexWrap: 'wrap' }}>
                <span style={{ fontSize: '.7rem', fontWeight: 500, background: 'var(--teal-lt)', color: 'var(--teal)', padding: '.18rem .55rem', borderRadius: 20, textTransform: 'uppercase', letterSpacing: '.04em' }}>ShikshaAI</span>
                <span style={{
                  fontSize: '.7rem', fontWeight: 500, padding: '.18rem .55rem', borderRadius: 20,
                  background: difficulty === 'easy' ? 'var(--green-lt)' : difficulty === 'hard' ? 'var(--red-lt)' : 'var(--saffron-lt)',
                  color: difficulty === 'easy' ? 'var(--green)' : difficulty === 'hard' ? 'var(--red)' : 'var(--saffron)',
                }}>
                  {difficulty.charAt(0).toUpperCase() + difficulty.slice(1)}
                </span>
                {result.from_cache && (
                  <span style={{ fontSize: '.7rem', fontWeight: 500, background: 'var(--blue-lt)', color: 'var(--blue)', padding: '.18rem .55rem', borderRadius: 20 }}>⚡ Cached</span>
                )}
              </div>

              {/* Answer bubble */}
              <div style={{
                background: 'var(--paper)', border: '1px solid var(--border)',
                borderLeft: '3px solid var(--teal)', borderRadius: '0 9px 9px 9px',
                padding: '1rem 1.15rem', fontSize: '.93rem', lineHeight: 1.75,
                color: 'var(--ink)', fontFamily: "'Lora', serif",
              }}>
                {result.answer}
              </div>

              {/* Actions */}
              <div style={{ display: 'flex', gap: '.5rem', flexWrap: 'wrap', marginTop: '.75rem' }}>
                <button onClick={() => speak(result.answer)} style={outlineBtnStyle}>
                  {isSpeaking ? '⏹ Stop Reading' : '🔊 Read Aloud'}
                </button>
                <button onClick={() => downloadTxt(question, selectedSubject, difficulty, result.answer)} style={outlineBtnStyle}>
                  ⬇ Download Answer
                </button>
              </div>

              {/* Cost metrics */}
              <div style={{ height: 1, background: 'var(--border)', margin: '1rem 0' }} />
              <div style={{ display: 'flex', alignItems: 'center', gap: '.45rem', marginBottom: '.75rem', fontFamily: "'Lora', serif", fontSize: '.88rem', fontWeight: 600, color: 'var(--ink)' }}>
                <span style={iconStyle}>💰</span> Cost Savings
              </div>
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: '.6rem', marginBottom: '.75rem' }}>
                {[
                  { label: 'Baseline tokens', val: result.original_tokens_est?.toLocaleString(), cls: '' },
                  { label: 'Pruned tokens',   val: result.pruned_tokens_est?.toLocaleString(),  cls: 'used' },
                  { label: 'Cost saved',       val: result.cost_saved_pct + '%',                  cls: 'saved' },
                ].map(m => (
                  <div key={m.label} style={{ background: 'var(--paper)', border: '1px solid var(--border)', borderRadius: 7, padding: '.65rem', textAlign: 'center' }}>
                    <span style={{ fontSize: '1.2rem', fontWeight: 500, color: m.cls === 'saved' ? 'var(--teal)' : m.cls === 'used' ? 'var(--saffron)' : 'var(--ink)', fontFamily: "'Lora', serif", display: 'block', lineHeight: 1.1 }}>{m.val}</span>
                    <div style={{ fontSize: '.7rem', color: 'var(--ink-muted)', marginTop: '.2rem', textTransform: 'uppercase', letterSpacing: '.04em' }}>{m.label}</div>
                  </div>
                ))}
              </div>

              {/* Savings bar */}
              <div style={{ background: 'var(--paper-3)', borderRadius: 4, height: 5, overflow: 'hidden', marginBottom: '.3rem' }}>
                <div style={{ height: '100%', background: 'var(--teal)', borderRadius: 4, width: `${Math.min(result.cost_saved_pct, 100)}%`, transition: 'width .8s cubic-bezier(.4,0,.2,1)' }} />
              </div>
              <p style={{ fontSize: '.72rem', color: 'var(--teal)', fontWeight: 500, marginBottom: '.3rem' }}>
                {result.cost_saved_pct}% fewer tokens vs baseline RAG
              </p>
              <p style={{ fontSize: '.76rem', color: 'var(--ink-muted)' }}>
                Pruner kept {result.sentences_kept} of {result.sentences_total} sentences.
              </p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

const cardStyle = {
  background: 'var(--surface)', border: '1px solid var(--border)',
  borderRadius: 'var(--radius)', padding: '1.25rem',
  boxShadow: 'var(--shadow)', animation: 'riseIn .35s ease both',
}

const inputStyleLocal = {
  width: '100%', padding: '.6rem .8rem',
  border: '1px solid var(--border)', borderRadius: 7,
  background: 'var(--paper)', fontFamily: "'DM Sans', sans-serif",
  fontSize: '.9rem', color: 'var(--ink)', outline: 'none',
}

const outlineBtnStyle = {
  display: 'inline-flex', alignItems: 'center', justifyContent: 'center', gap: '.4rem',
  padding: '.35rem .75rem', borderRadius: 7,
  fontFamily: "'DM Sans', sans-serif", fontSize: '.78rem', fontWeight: 500,
  cursor: 'pointer', background: 'transparent',
  border: '1px solid var(--border)', color: 'var(--ink-soft)', transition: 'all .18s',
}
